# Generated by Django 3.0 on 2020-01-07 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('categories_and_labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=60)),
                ('image', models.CharField(default='a/b/c', max_length=255)),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_labels.Label')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop')),
            ],
        ),
    ]
