# Generated by Django 3.0 on 2020-01-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.NullBooleanField(choices=[(None, 'Speding'), (True, 'Confirmed'), (False, 'cancelled')], default=None, max_length=60)),
                ('payment', models.CharField(default='cash', max_length=60)),
                ('VAT', models.FloatField(default=1.5)),
                ('ship', models.DecimalField(decimal_places=3, max_digits=60)),
                ('total', models.DecimalField(decimal_places=3, max_digits=60)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
