# Generated by Django 3.0 on 2019-12-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20191225_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='ship',
            field=models.DecimalField(decimal_places=3, max_digits=60),
        ),
    ]
