# Generated by Django 3.0 on 2020-01-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartDetail',
        ),
    ]
