# Generated by Django 3.0 on 2020-01-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='name',
        ),
    ]
