# Generated by Django 3.0 on 2019-12-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
