# Generated by Django 3.0.1 on 2019-12-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191223_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[(0, 'waiting'), (1, 'actived'), (-1, 'rejected')], default='spending', max_length=30),
        ),
    ]
