# Generated by Django 3.0 on 2019-12-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20191228_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='a/b/c', max_length=255),
        ),
    ]
