# Generated by Django 3.0.1 on 2019-12-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('number', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('image', models.CharField(default='a/b/c', max_length=30)),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Label')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Shop')),
            ],
        ),
    ]
