# Generated by Django 3.0 on 2019-12-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_bill_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='ship',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Product', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
    ]
